import { ArrowRight, CheckCircle2, ChevronRight, ClipboardCheck, ClipboardList, Clock3, Pencil, Send } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { AdminShell } from "../../../components/layout";
import { Avatar, PageToolbar, StatusPill, Toast, ToastMessage } from "../../../components/ui";
import type { Exam, ReviewQueueItem } from "../../../domain/models";
import { examRepository } from "../../../repositories";

export function ReviewsPage() {
  const [search, setSearch] = useState("");
  const [exam, setExam] = useState<Exam | null>(null);
  const [queue, setQueue] = useState<ReviewQueueItem[]>([]);
  const [toast, setToast] = useState<Toast | null>(null);
  useEffect(() => { examRepository.list().then(exams => { const selected = exams.find(item => item.mode === "Koreksi admin" && item.status !== "Draf") || null; setExam(selected); if (selected) return examRepository.reviewQueue(String(selected.id)).then(rows => setQueue(rows.map(row => ({ id: row.attempt.id, studentId: row.student.id, name: row.student.name, class: String(row.student.grade), status: row.attempt.gradingStatus === "released" ? "Sudah terbit" : row.attempt.gradingStatus === "reviewed" ? "Siap diterbitkan" : row.attempt.gradingStatus === "in_review" ? "Sedang dikoreksi" : "Belum dikoreksi", reviewedCount: row.reviewedCount, totalQuestions: row.questionCount, progress: `${row.reviewedCount}/${row.questionCount}`, submittedAt: row.attempt.submittedAt ? new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(row.attempt.submittedAt)) : "-" })))); }); }, []);
  const summary = useMemo(() => ({ total: queue.length, pending: queue.filter(item => item.status === "Belum dikoreksi").length, inReview: queue.filter(item => item.status === "Sedang dikoreksi").length, completed: queue.filter(item => ["Siap diterbitkan", "Sudah terbit"].includes(item.status)).length }), [queue]);
  const filtered = queue.filter(item => item.name.toLowerCase().includes(search.toLowerCase()));
  return <AdminShell title="Koreksi jawaban" subtitle="Periksa jawaban peserta dan terbitkan nilai.">{toast && <ToastMessage toast={toast} onClose={() => setToast(null)} />}<div className="review-alert"><span><ClipboardCheck /></span><div><strong>{summary.pending} peserta menunggu koreksi</strong><p>{exam?.title || "Belum ada ujian koreksi admin yang diterbitkan."}</p></div>{queue[0] && <Link className="button secondary" to={`/admin/reviews/${queue[0].id}`}>Mulai koreksi <ArrowRight /></Link>}</div><div className="review-summary-grid"><div><span className="gray"><ClipboardList /></span><p><strong>{summary.total}</strong><small>Total antrean</small></p></div><div><span className="orange"><Clock3 /></span><p><strong>{summary.pending}</strong><small>Belum dikoreksi</small></p></div><div><span className="purple"><Pencil /></span><p><strong>{summary.inReview}</strong><small>Sedang dikoreksi</small></p></div><div><span className="green"><CheckCircle2 /></span><p><strong>{summary.completed}</strong><small>Selesai dikoreksi</small></p></div></div><section className="panel table-panel"><PageToolbar search={search} setSearch={setSearch} placeholder="Cari nama peserta..."><button className="button secondary" disabled={!exam} onClick={async () => { if (!exam) return; const released = await examRepository.releaseResults(String(exam.id)); setToast({ message: `${released.length} hasil diterbitkan` }); }}><Send /> Terbitkan batch</button></PageToolbar><div className="table-scroll"><table><thead><tr><th>Peserta</th><th>Kelas</th><th>Waktu submit</th><th>Progres koreksi</th><th>Status</th><th /></tr></thead><tbody>{filtered.map(item => <tr key={item.id}><td><div className="person-cell"><Avatar name={item.name} /><strong>{item.name}</strong></div></td><td>{item.class}</td><td>{item.submittedAt}</td><td><div className="review-progress"><span>{item.reviewedCount}/{item.totalQuestions}</span><div><i style={{ width: `${item.totalQuestions ? item.reviewedCount / item.totalQuestions * 100 : 0}%` }} /></div></div></td><td><StatusPill tone={item.status === "Belum dikoreksi" ? "nonaktif" : item.status === "Sedang dikoreksi" ? "warning" : item.status === "Sudah terbit" ? "terbit" : "aktif"}>{item.status}</StatusPill></td><td><Link to={`/admin/reviews/${item.id}`} className="button small secondary">Buka <ChevronRight /></Link></td></tr>)}</tbody></table></div></section></AdminShell>;
}
